<?php
/*
 * Generated configuration file
 * Generated by: phpMyAdmin 4.4.11 setup script
 * Date: Thu, 06 Aug 2015 12:28:37 +0000
 */

/* Servers configuration */
$i = 0;

/* Server: DB [1] */
$i++;
$cfg['Servers'][$i]['verbose'] = 'DB STAGING';
$cfg['Servers'][$i]['host'] = 'stagingjojodb.cedsh6izjwsr.ap-northeast-1.rds.amazonaws.com';
$cfg['Servers'][$i]['port'] = '';
$cfg['Servers'][$i]['socket'] = '';
$cfg['Servers'][$i]['connect_type'] = 'tcp';
$cfg['Servers'][$i]['auth_type'] = 'cookie';
$cfg['Servers'][$i]['user'] = 'root';
$cfg['Servers'][$i]['password'] = '';
$cfg['Servers'][$i]['only_db'] = array('pinnacle');


$i++;
$cfg['Servers'][$i]['verbose'] = 'DB PROD';
$cfg['Servers'][$i]['host'] = 'jojo008db.cedsh6izjwsr.ap-northeast-1.rds.amazonaws.com';
$cfg['Servers'][$i]['port'] = '';
$cfg['Servers'][$i]['socket'] = '';
$cfg['Servers'][$i]['connect_type'] = 'tcp';
$cfg['Servers'][$i]['auth_type'] = 'cookie';
$cfg['Servers'][$i]['user'] = 'root';
$cfg['Servers'][$i]['password'] = '';
$cfg['Servers'][$i]['only_db'] = array('pinnacle');



/* End of servers configuration */

$cfg['blowfish_secret'] = '55c3529e3cd639.93728374';
$cfg['DefaultLang'] = 'en';
$cfg['ServerDefault'] = 1;
$cfg['UploadDir'] = '';
$cfg['SaveDir'] = '';
$cfg['MaxNavigationItems']='100';
?>
